[versions]
kotlin = "2.3.0-RC2"
quickMpp = "0.21"

[libraries]
objectPool = { module = "io.github.adokky:object-pool", version = "1.0" }
bitvector = { module = "io.github.adokky:bitvector", version = "0.9.2" }
equalsTester = { module = "io.github.adokky:equals-tester", version = "1.1.0" }
karamelUtils-core = { module = "io.github.adokky:karamel-utils-core", version = "0.2.0" }
karamelUtils-tsbits = { module = "io.github.adokky:karamel-utils-ts-bits", version = "0.1.1" }

[plugins]
quick-mpp = { id = "io.github.adokky.quick-mpp", version.ref = "quickMpp" }
quick-jvm = { id = "io.github.adokky.quick-jvm", version.ref = "quickMpp" }
quick-publish = { id = "io.github.adokky.quick-publish", version.ref = "quickMpp" }